version: "3.8"
services:
  backend:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/var/www/site
    depends_on:
      - redis 
    command: python3 /var/www/site/app/wsgi.py

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

