version: "3.8"
services:
  backend:
    build: .
    image: docker.io/seraua09/test:${TAG}
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/backend
    depends_on:
      - redis 

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

