version: "3.8"
services:
  site:
    build: .
    ports:
      - "80:80"
    networks:
      vpcbr:
        ipv4_address: 10.10.0.3

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      vpcbr:
        ipv4_address: 10.10.0.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.1/24
         gateway: 10.10.0.1
