version: "3.8"
services:
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/backend
    depends_on:
      - redis 

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.1/24
         gateway: 10.10.0.1
