version: "3.8"
services:
  backend:
    image: docker.io/seraua09/test
    ports:
      - "80:5000"
    volumes:
      - ./:/var/www/backend
    depends_on:
      - redis 
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

