---
- name: "Copy docker-compose to server"
  ansible.builtin.copy:
    src: ../docker-compose.prod.yml
    dest: "/var/"

- name: "Log in to docker-hub"
  shell:
    cmd: "docker login -u {{ docker_user }} -p {{ docker_password }}"
- name: Update application image
  shell:
    chdir: "/var/"
    cmd: "docker-compose -f docker-compose.prod.yml pull {{ project }}"
- name: "Rebuild docker-compose"
  shell:
    chdir: "/var/"
    cmd: docker-compose -f docker-compose.prod.yml build
- name: "Up docker container"
  shell:
    chdir: "/var/"
    cmd: docker-compose -f docker-compose.prod.yml up -d