---

- name: "Copy docker-compose to server"
  ansible.builtin.copy:
    src: /home/runner/work/site/site/docker-compose.prod.yml
    dest: "/var/www/{{ project }}"

- name: "Log in to docker-hub"
  shell:
    cmd: "docker login -u {{ docker_user }} -p {{ docker_password }}"
- name: Update application image
  shell:
    cmd: "docker-compose pull {{ project }}"
- name: "Rebuild docker-compose"
  shell:
    cmd: docker-compose -f docker-compose.prod.yml