name: Remote SSH Deployment
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh command via HOST IP, HOST USERNAME and SSH PRIVATE KEY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            git clone git@github.com:seraus09/site.git
            cd site
            docker built -t site && docker run -d -p 80:80 site
